### ISSUE TITLE
Contact Page (on the Jamstack)

### ISSUE THREAD

**Issue by thescientist13** [AnalogStudiosRI/www.analogstudios.net#29]
## Type of Change
- [ ] New Feature Request
- [x] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
As part of the migration in #12 and moving to Netlify hosting , we will need to persist the Contact page in a Jamstack fashion.

## Details
I was thinking a perfect opportunity to try [Netlify Forms](https://docs.netlify.com/forms/setup/)?  🤩

**Comment by aholtzman** [comment]
@thescientist13 Netlify Forms work well but if you wanted something more custom you can use Netlify Functions - I use this for my personal site...
```
const nodemailer = require("nodemailer")
require("dotenv").config()

const { GMAIL_KEY } = process.env

exports.handler = function (event, context, callback) {
  const data = [...JSON.parse(event.body)]

  const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: "myemail@gmail.com",
      pass: GMAIL_KEY,
    },
  })

  const list = `<ul>${data.map(i => {
    const key = Object.keys(i)[0]
    return `<li>${key}: ${i[key]}</li>`
  })}</ul>`

  const mailOptions = {
    from: "youremail@gmail.com",
    to: "myemail@gmail.com",
    subject: "Form submission from mysite.com",
    html: list,
  }

  transporter.sendMail(mailOptions, function (error, info) {
    if (error) {
      callback(error)
    } else {
      callback(null, {
        statusCode: 200,
        body: JSON.stringify({
          result: "success",
        }),
      })
    }
  })
}
```

**Comment by thescientist13** [comment]
Oh this, is great!  Yeah, I was wondering down the road in a more serverless / hybrid capacity where the site might not be running on Netlify, what an option for that is, and seems like just make a serverless function for it.  Excellent, will definitely make use of that snippet.  👌
