### ISSUE TITLE
add typing for Google Analytics (`ga`) global variable

### ISSUE THREAD

**Issue by thescientist13** [AnalogStudiosRI/www.analogstudios.net#92]
## Type of Change
- [ ] New Feature Request
- [ ] Improvement / Suggestion
- [ ] Bug
- [x] Other (please clarify below)

## Summary
Currently the use of the Google Analytics `ga` global variables shows the red squiggly lines from TypeScript
<img width="1314" alt="Screenshot 2023-11-02 at 9 46 59 PM" src="https://github.com/AnalogStudiosRI/www.analogstudios.net/assets/895923/4f5a9160-abe9-44c2-9708-769b70f0a3fe">
```js
connectedCallback(): void {
  super.connectedCallback();

  ga('set', 'page', '/events');
  ga('send', 'pageview');
}
```

## Details
Would be nice to
<img width="434" alt="Screenshot 2023-11-02 at 9 49 04 PM" src="https://github.com/AnalogStudiosRI/www.analogstudios.net/assets/895923/2f73c38c-c20d-4dd7-b5be-36ef354c8c99">
 find a solution to fix all usages!

**Comment by uwemneku** [comment]
Hi, not sure if a PR is required but adding `@types/google.analytics` to the project atomatically fixes all TS errors with the `ga` variable and correctly types it

**Comment by uwemneku** [comment]
Hi @thescientist13 , adding `@types/google.analytics` to the project atomatically fixes all TS errors with the `ga` variable and correctly types it. 

Not sure if a PR is required

**Comment by thescientist13** [comment]
Hey @uwemneku , that's great to hear!  I think a PR would be good, I think adding those types as a dev dependency probably?
